### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by fuzzy76** [riicchhaarrd/CoDExtended#5]
I can't find a description anywhere of what CoDExtended _actually_ does. Which hacks, what limits, which bugs... Is there a feature list somewhere?

**Comment by marcmascarell** [comment]
I think that this is pretty abandonded, sadly. Also not much documented at all, avoiding others to help...

**Comment by riicchhaarrd** [comment]
The stable or master is targeted at a very specific version of the first installment of the Call of Duty game (Patch 1.1 Linux Dedicated), where as the people who actually use this (there's quite some still apparently) know what it does and what it is for. I kinda lost interest for it and it's indeed abandoned I suppose. 

In previous README files I had listed some features and such, and there's still some old working code in the other branch (Windows/Linux 1.1/1.5), but I just put a general text on it due to not thinking people would really care for such a niche community.

Copied from previous version of README;

Features:
 
 - GSC > C/C++
 - Extending the functions/methods of the default GSC script
 - New memberfields additions
 - Various callbacks e.g ClientCommand
 - Bugfixes e.g (q3dirtrav (downloading of server config files and such RCON))
 - Much more unlisted features
-
-:: Player Features
 - Collision (If the collision is turned off then you can stand ontop of other people. ;])
 - Velocity altering
 - Instead of the self.angles > self getplayerangles() which returns better angles (x,y,z) instead of just y
 - Play player-animation(s) with a script
-
-:: Entity features
 - Entity collision and damage feedback
